name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 0' # every Sunday at 3am

env:
  CI: true

jobs:
  lint_js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: ESLint
        run: pnpm lint

  test_type_checking:
    name: 'Tests: Type Check'
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm tsc --noEmit
        working-directory: tests

  tests:
    name: Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # how to say "not these" so we don't miss anything?
        # waiting on a an api from vitest for querying
        # the list of tests ahead of time before running them.
        slow-test:
          - defaults with npm
          - defaults with yarn
          - defaults with pnpm
          - addon-location
          - test-app-location
          - typescript
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      # use ember-cli 4.10.0 beta, as this version is the first to support --typescript properly. @todo Revert this when 4.10.0 is stable      
      - run: pnpm add --global ember-cli@beta yarn
      - run: pnpm vitest --testNamePattern "${{ matrix.slow-test }}"
        working-directory: tests
